import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex } from "@chakra-ui/layout";
import ProfileCard from "../src/flat/ProfileCard";
import { ProfileInterface } from "../src/flat/Profile/interface";
import Carousel from "../src/features/Carousel";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [profiles, setProfiles] = useState<ProfileInterface[]>([]);

  useEffect(() => {
    let url =
      "https://api.sheety.co/6db0166e73d47e215afcb6675c9f83d9/test/sheet";
    fetch(url)
      .then((response) => response.json())
      .then((json) => {
        // Do something with the data
        console.log(json.sheet);
        setProfiles(json.sheet);
      });
  }, []);

  console.log("profiles", profiles);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexFlow="column" alignItems="center" w="100%">
        <Carousel
          items={profiles.map((profile) => {
            return (
              <React.Fragment key={profile.id}>
                <ProfileCard
                  profile={profile}
                  profiles={profiles}
                  setProfiles={setProfiles}
                />
              </React.Fragment>
            );
          })}
        />
        {}
      </Flex>
    </div>
  );
};

export default Home;
